### ISSUE TITLE
.array and .arrayValue functions?

### ISSUE THREAD

**Issue by lpbas** [akatkov7/KotlinyJSON#1]
I would like to thank you for this library. Coming for long use of the SwiftyJSon library I can say that I was really missing such a functionality on Kotlin and I'm glad I found this library.

However, I'm trying to get an array form a json object (it's an object that contains an array) but I can't seem to find the .array and .arrayValue methods that exist in SwiftyJson but not in this.

Also I think it would be nice to make the JSON(jsonArray: JSONArray) constructor public, since it would be a nice way to wrap an org.JSON array into your "KJSON" array. (A constructor that gets an org.JSON object and wraps it into your JSON would be very useful as well)

**Comment by akatkov7** [comment]
Hey @L4grange, thanks for the feedback! I believe that `.list` should work similarly to `.array` in SwiftyJSON. Let me know if that works for you. There isn't an `arrayValue` equivalent though. Adding that and more constructor options sounds useful. I don't have a lot of time to dedicate to this project so if you're interested in making a PR for that functionality, I'll find some time to review it; otherwise, I'll look into it when I get a chance.

**Comment by lpbas** [comment]
Thank you @akatkov7 , in my project I've created the .listValue as an extension and I've been using your library the same way I'm using SwiftyJSON, so I will create a PR when I get the time so you can add those changes!

**Comment by lpbas** [comment]
I've created PR #2 take a look when you find the time :)

**Comment by akatkov7** [comment]
Closed with #2
